### ISSUE TITLE
stripes 1.7b3 ignoring validationErrorHandler

### ISSUE THREAD

**Issue by currupipi-smith** [StripesFramework/stripes#60]
Hi,

relatively new to github and Stripes, which btw rocks. Using latest Stripes' beta, noticed that if a Restactionbean implements ValidationErrorHandler where the validation method returns my resolution, it gets ignored. I've noticed PR https://github.com/StripesFramework/stripes/pull/56 which seems related, but I don't know Stripes internals that well, so i don't really know.

How can I return a custom resolution on an error when executing a RestActionBean, how may I proceed?

Many thanks in advance,
pierre

**Comment by vankeisb** [comment]
Hi Pierre,

Although I haven't tried it myself, it definitely looks like the bug
described by Juan Pablo. I can't merge his fix right now because a test is
failing, but I guess it'll be fixed soon. I'll do another release then.

In the meantime, if this is a blocker for you, maybe you can just do the
validation logic right inside your even handler method (ie add errors to
the ActionBeanContext and/or return a Resolution of your own) ?

HTH

Rémi


2016-06-15 16:12 GMT+02:00 currupipi-smith <notifications@github.com>:

**Comment by currupipi-smith** [comment]
Hi Rémi,

thanks for your prompt response, will do as advised until the new beta is out.

cheers,
Pierre

**Comment by currupipi-smith** [comment]
Hi,

closing the issue as 1.7.0-beta4 is out.

cheers,
Pierre
